// <auto-generated />
using System;
using Backend.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace backend.Migrations
{
    [DbContext(typeof(HospitalContext))]
    [Migration("20220111191804_managerMigration")]
    partial class managerMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Backend.Entities.Availability", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<DateTime>("endDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("medicid")
                        .HasColumnType("integer");

                    b.Property<DateTime>("startDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("id");

                    b.HasIndex("medicid");

                    b.ToTable("Availabilities");
                });

            modelBuilder.Entity("Backend.Entities.Clinic", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("mail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("menager_id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("specializationid")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("specializationid");

                    b.ToTable("Clinics");
                });

            modelBuilder.Entity("Backend.Entities.Manager", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("PESEL")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("mail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Managers");
                });

            modelBuilder.Entity("Backend.Entities.Medic", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("PESEL")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("mail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("medicRole")
                        .HasColumnType("integer");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Medics");
                });

            modelBuilder.Entity("Backend.Entities.Patient", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("PESEL")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("insuranceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("mail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("Backend.Entities.Receptionist", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("PESEL")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("clinicid")
                        .HasColumnType("integer");

                    b.Property<string>("mail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("clinicid");

                    b.ToTable("Receptionists");
                });

            modelBuilder.Entity("Backend.Entities.Specialization", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("description")
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Specializations");
                });

            modelBuilder.Entity("Backend.Entities.Visit", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("description")
                        .HasColumnType("text");

                    b.Property<int?>("patientid")
                        .HasColumnType("integer");

                    b.Property<int?>("receptionistid")
                        .HasColumnType("integer");

                    b.Property<DateTime>("startDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("workingTimeid")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("patientid");

                    b.HasIndex("receptionistid");

                    b.HasIndex("workingTimeid");

                    b.ToTable("Visits");
                });

            modelBuilder.Entity("Backend.Entities.WorkingTime", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<int?>("clinicid")
                        .HasColumnType("integer");

                    b.Property<DateTime>("endDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("medicid")
                        .HasColumnType("integer");

                    b.Property<DateTime>("startDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("id");

                    b.HasIndex("clinicid");

                    b.HasIndex("medicid");

                    b.ToTable("WorkingTimes");
                });

            modelBuilder.Entity("ClinicMedic", b =>
                {
                    b.Property<int>("clinicsid")
                        .HasColumnType("integer");

                    b.Property<int>("medicsid")
                        .HasColumnType("integer");

                    b.HasKey("clinicsid", "medicsid");

                    b.HasIndex("medicsid");

                    b.ToTable("ClinicMedic");
                });

            modelBuilder.Entity("MedicSpecialization", b =>
                {
                    b.Property<int>("medicsid")
                        .HasColumnType("integer");

                    b.Property<int>("specializationsid")
                        .HasColumnType("integer");

                    b.HasKey("medicsid", "specializationsid");

                    b.HasIndex("specializationsid");

                    b.ToTable("MedicSpecialization");
                });

            modelBuilder.Entity("Backend.Entities.Availability", b =>
                {
                    b.HasOne("Backend.Entities.Medic", "medic")
                        .WithMany()
                        .HasForeignKey("medicid");

                    b.Navigation("medic");
                });

            modelBuilder.Entity("Backend.Entities.Clinic", b =>
                {
                    b.HasOne("Backend.Entities.Specialization", "specialization")
                        .WithMany()
                        .HasForeignKey("specializationid");

                    b.Navigation("specialization");
                });

            modelBuilder.Entity("Backend.Entities.Receptionist", b =>
                {
                    b.HasOne("Backend.Entities.Clinic", "clinic")
                        .WithMany()
                        .HasForeignKey("clinicid");

                    b.Navigation("clinic");
                });

            modelBuilder.Entity("Backend.Entities.Visit", b =>
                {
                    b.HasOne("Backend.Entities.Patient", "patient")
                        .WithMany()
                        .HasForeignKey("patientid");

                    b.HasOne("Backend.Entities.Receptionist", "receptionist")
                        .WithMany()
                        .HasForeignKey("receptionistid");

                    b.HasOne("Backend.Entities.WorkingTime", "workingTime")
                        .WithMany()
                        .HasForeignKey("workingTimeid");

                    b.Navigation("patient");

                    b.Navigation("receptionist");

                    b.Navigation("workingTime");
                });

            modelBuilder.Entity("Backend.Entities.WorkingTime", b =>
                {
                    b.HasOne("Backend.Entities.Clinic", "clinic")
                        .WithMany()
                        .HasForeignKey("clinicid");

                    b.HasOne("Backend.Entities.Medic", "medic")
                        .WithMany()
                        .HasForeignKey("medicid");

                    b.Navigation("clinic");

                    b.Navigation("medic");
                });

            modelBuilder.Entity("ClinicMedic", b =>
                {
                    b.HasOne("Backend.Entities.Clinic", null)
                        .WithMany()
                        .HasForeignKey("clinicsid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Entities.Medic", null)
                        .WithMany()
                        .HasForeignKey("medicsid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MedicSpecialization", b =>
                {
                    b.HasOne("Backend.Entities.Medic", null)
                        .WithMany()
                        .HasForeignKey("medicsid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Entities.Specialization", null)
                        .WithMany()
                        .HasForeignKey("specializationsid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
